config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  
  resources :documents
  authenticated :user do
    root 'documents#index', as: 'authenticated_root'
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :find_document, only: [:edit, :update, :show, :destroy]

  def index
    @docs = Document.where(user_id: current_user)
  end

  def show
  end

  def new
    @document = current_user.documents.build
  end
  
  def create
    @document = current_user.documents.build(document_params)

    if @document.save
      redirect_to @document
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @document.update(document_params)
      redirect_to @document
    else
      render "edit"
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_path
  end

  private 

    def find_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:tittle, :content)
    end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/_form.html.haml
= simple_form_for @document do |f|
  = f.input :tittle
  = f.input :content
  = f.button :submit

app/views/documents/edit.html.haml
%h1 Fix Document

= render "form"

= link_to "Cancel", document_path

app/views/documents/index.html.haml
- @docs.each do |doc|
  %h2= link_to doc.tittle, doc
  %p= truncate(doc.content, length:50)
  %p= time_ago_in_words(doc.created_at)

= link_to "Create Document", new_document_path

app/views/documents/new.html.haml
%h1 New Document!

= render "form"

app/views/documents/show.html.haml
= javascript_include_tag 

%h1= @document.tittle
%p= @document.content

= link_to "All Documents", documents_path
= link_to "Fix Doc", edit_document_path(@document)
= button_to "Delete It", document_path(@document), method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cabinet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.haml
%h1 El placeholder